kind: ConfigMap
apiVersion: v1
metadata:
  name: dns1-config
  namespace: dns
data:
  managed-zones.conf: ''
  named.conf.options: "options {\n\tdirectory \"/var/cache/bind\";\n\tallow-query { any; };\n\tallow-transfer { any; };\n\tforwarders { 8.8.8.8; 8.8.4.4; };\n\trecursion yes;\n\tlisten-on { any; };\n\tlisten-on-v6 { any; };\n};"
  rndc.key: "key \"rndc-key\" {\n\talgorithm hmac-sha256;\n\tsecret \"c3VwZXJzZWNyZXQK\";\n};"
