apiVersion: v1
kind: Service
metadata:
  name: dns1-ui
  namespace: dns
spec:
  selector:
    app: dns1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dns1-bind
  namespace: dns
spec:
  type: LoadBalancer
  selector:
    app: dns1
  ports:
    - name: 53-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: 53-udp
      protocol: UDP
      port: 53
      targetPort: 53
